<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8rXWesy\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8rXWesy/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8rXWesy.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8rXWesy\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \Container8rXWesy\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => '8rXWesy',
    'container.build_id' => 'f625310b',
    'container.build_time' => 1685993218,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8rXWesy');
