<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUr8rJs\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUr8rJs/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEUr8rJs.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEUr8rJs\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerEUr8rJs\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'EUr8rJs',
    'container.build_id' => '2a5275bd',
    'container.build_time' => 1683032674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUr8rJs');
