<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPy5di3c\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPy5di3c/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPy5di3c.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPy5di3c\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerPy5di3c\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'Py5di3c',
    'container.build_id' => 'ab3c3508',
    'container.build_time' => 1684688959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPy5di3c');
