<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUP5hNlY\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUP5hNlY/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUP5hNlY.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUP5hNlY\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerUP5hNlY\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'UP5hNlY',
    'container.build_id' => 'c8f27f83',
    'container.build_time' => 1684689023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUP5hNlY');
