<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXymlwhT\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXymlwhT/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXymlwhT.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXymlwhT\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerXymlwhT\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'XymlwhT',
    'container.build_id' => '3307a63e',
    'container.build_time' => 1683032110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXymlwhT');
