controllers:
    resource: ../src/Controller/
    type: attribute

#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number

index:
    path: /
    controller: App\Controller\IndexPage::index
    schemes: [https]

login:
    path: /login
    controller: App\Controller\Login::login
    schemes: [https]

register:
    path: /register
    controller: App\Controller\Register::Register
    schemes: [https]