<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3FeuFSp\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3FeuFSp/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3FeuFSp.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3FeuFSp\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \Container3FeuFSp\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => '3FeuFSp',
    'container.build_id' => 'bc5924dc',
    'container.build_time' => 1686266750,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3FeuFSp');
