<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationRequirementsValidatorService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the private 'Shopware\Core\Installer\Requirements\ConfigurationRequirementsValidator' shared service.
     *
     * @return \Shopware\Core\Installer\Requirements\ConfigurationRequirementsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Requirements/RequirementsValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Requirements/ConfigurationRequirementsValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Requirements/IniConfigReader.php';

        return $container->privates['Shopware\\Core\\Installer\\Requirements\\ConfigurationRequirementsValidator'] = new \Shopware\Core\Installer\Requirements\ConfigurationRequirementsValidator(new \Shopware\Core\Installer\Requirements\IniConfigReader());
    }
}
