<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseConfigurationControllerService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the public 'Shopware\Core\Installer\Controller\DatabaseConfigurationController' shared service.
     *
     * @return \Shopware\Core\Installer\Controller\DatabaseConfigurationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/InstallerController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/DatabaseConfigurationController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Database/BlueGreenDeploymentService.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Maintenance/System/Service/JwtCertificateGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Maintenance/System/Service/SetupDatabaseAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Maintenance/System/Service/DatabaseConnectionFactory.php';

        $container->services['Shopware\\Core\\Installer\\Controller\\DatabaseConfigurationController'] = $instance = new \Shopware\Core\Installer\Controller\DatabaseConfigurationController(($container->services['translator'] ?? $container->load('getTranslatorService')), new \Shopware\Core\Installer\Database\BlueGreenDeploymentService(), ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\JwtCertificateGenerator'] ?? ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\JwtCertificateGenerator'] = new \Shopware\Core\Maintenance\System\Service\JwtCertificateGenerator())), ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\SetupDatabaseAdapter'] ?? ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\SetupDatabaseAdapter'] = new \Shopware\Core\Maintenance\System\Service\SetupDatabaseAdapter())), ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\DatabaseConnectionFactory'] ?? ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\DatabaseConnectionFactory'] = new \Shopware\Core\Maintenance\System\Service\DatabaseConnectionFactory())), \dirname(__DIR__, 4));

        $instance->setContainer($container);

        return $instance;
    }
}
