<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvironmentRequirementsValidatorService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the private 'Shopware\Core\Installer\Requirements\EnvironmentRequirementsValidator' shared service.
     *
     * @return \Shopware\Core\Installer\Requirements\EnvironmentRequirementsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Requirements/RequirementsValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Requirements/EnvironmentRequirementsValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/composer/composer/src/Composer/Composer.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Framework/Plugin/Composer/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/composer/composer/src/Composer/Repository/RepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/composer/composer/src/Composer/Repository/PlatformRepository.php';

        return $container->privates['Shopware\\Core\\Installer\\Requirements\\EnvironmentRequirementsValidator'] = new \Shopware\Core\Installer\Requirements\EnvironmentRequirementsValidator(\Shopware\Core\Framework\Plugin\Composer\Factory::createComposer(\dirname(__DIR__, 4)), new \Composer\Repository\PlatformRepository());
    }
}
