<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinishControllerService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the public 'Shopware\Core\Installer\Controller\FinishController' shared service.
     *
     * @return \Shopware\Core\Installer\Controller\FinishController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/InstallerController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/FinishController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Finish/SystemLocker.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';

        $container->services['Shopware\\Core\\Installer\\Controller\\FinishController'] = $instance = new \Shopware\Core\Installer\Controller\FinishController(new \Shopware\Core\Installer\Finish\SystemLocker(\dirname(__DIR__, 4)), ($container->privates['Shopware\\Core\\Installer\\Finish\\Notifier'] ?? $container->load('getNotifierService')), ($container->privates['GuzzleHttp\\Client'] ?? ($container->privates['GuzzleHttp\\Client'] = new \GuzzleHttp\Client())), $container->getEnv('string:APP_URL'));

        $instance->setContainer($container);

        return $instance;
    }
}
