<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLicenseControllerService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the public 'Shopware\Core\Installer\Controller\LicenseController' shared service.
     *
     * @return \Shopware\Core\Installer\Controller\LicenseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/InstallerController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/LicenseController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/License/LicenseFetcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';

        $container->services['Shopware\\Core\\Installer\\Controller\\LicenseController'] = $instance = new \Shopware\Core\Installer\Controller\LicenseController(new \Shopware\Core\Installer\License\LicenseFetcher(new \GuzzleHttp\Client(), $container->parameters['shopware.installer.tosUrls']));

        $instance->setContainer($container);

        return $instance;
    }
}
