<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopConfigurationControllerService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the public 'Shopware\Core\Installer\Controller\ShopConfigurationController' shared service.
     *
     * @return \Shopware\Core\Installer\Controller\ShopConfigurationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/InstallerController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/ShopConfigurationController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Configuration/EnvConfigWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Configuration/ShopConfigurationService.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Configuration/AdminConfigurationService.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Maintenance/System/Service/DatabaseConnectionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Finish/UniqueIdGenerator.php';

        $container->services['Shopware\\Core\\Installer\\Controller\\ShopConfigurationController'] = $instance = new \Shopware\Core\Installer\Controller\ShopConfigurationController(($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\DatabaseConnectionFactory'] ?? ($container->privates['Shopware\\Core\\Maintenance\\System\\Service\\DatabaseConnectionFactory'] = new \Shopware\Core\Maintenance\System\Service\DatabaseConnectionFactory())), new \Shopware\Core\Installer\Configuration\EnvConfigWriter(\dirname(__DIR__, 4), ($container->privates['Shopware\\Core\\Installer\\Finish\\UniqueIdGenerator'] ?? ($container->privates['Shopware\\Core\\Installer\\Finish\\UniqueIdGenerator'] = new \Shopware\Core\Installer\Finish\UniqueIdGenerator(\dirname(__DIR__, 4))))), new \Shopware\Core\Installer\Configuration\ShopConfigurationService(), new \Shopware\Core\Installer\Configuration\AdminConfigurationService(), ($container->services['translator'] ?? $container->load('getTranslatorService')), $container->parameters['shopware.installer.supportedLanguages'], $container->parameters['shopware.installer.supportedCurrencies']);

        $instance->setContainer($container);

        return $instance;
    }
}
