<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopware_Asset_AssetService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the private 'shopware.asset.asset' shared service.
     *
     * @return \Shopware\Core\Framework\Adapter\Asset\FallbackUrlPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/PackageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/Package.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/UrlPackage.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Framework/Adapter/Asset/FallbackUrlPackage.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/VersionStrategy/VersionStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/VersionStrategy/EmptyVersionStrategy.php';

        return $container->privates['shopware.asset.asset'] = new \Shopware\Core\Framework\Adapter\Asset\FallbackUrlPackage([0 => ''], new \Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy());
    }
}
