<?php

namespace ContainerKF7Khg9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectLanguagesControllerService extends Shopware_Core_Installer_InstallerKernelDevDebugContainer
{
    /**
     * Gets the public 'Shopware\Core\Installer\Controller\SelectLanguagesController' shared service.
     *
     * @return \Shopware\Core\Installer\Controller\SelectLanguagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/InstallerController.php';
        include_once \dirname(__DIR__, 4).'/vendor/shopware/core/Installer/Controller/SelectLanguagesController.php';

        $container->services['Shopware\\Core\\Installer\\Controller\\SelectLanguagesController'] = $instance = new \Shopware\Core\Installer\Controller\SelectLanguagesController(($container->privates['Shopware\\Core\\Installer\\Finish\\Notifier'] ?? $container->load('getNotifierService')));

        $instance->setContainer($container);

        return $instance;
    }
}
