<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKF7Khg9\Shopware_Core_Installer_InstallerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKF7Khg9/Shopware_Core_Installer_InstallerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKF7Khg9.legacy');

    return;
}

if (!\class_exists(Shopware_Core_Installer_InstallerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKF7Khg9\Shopware_Core_Installer_InstallerKernelDevDebugContainer::class, Shopware_Core_Installer_InstallerKernelDevDebugContainer::class, false);
}

return new \ContainerKF7Khg9\Shopware_Core_Installer_InstallerKernelDevDebugContainer([
    'container.build_hash' => 'KF7Khg9',
    'container.build_id' => 'b3ee7ba8',
    'container.build_time' => 1683030534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKF7Khg9');
