<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'installer.database-configuration' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\DatabaseConfigurationController::databaseConfiguration'], [], [['text', '/installer/database-configuration']], [], [], []],
    'installer.database-information' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\DatabaseConfigurationController::databaseInformation'], [], [['text', '/installer/database-information']], [], [], []],
    'installer.database-import' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\DatabaseImportController::databaseImport'], [], [['text', '/installer/database-import']], [], [], []],
    'installer.database-migrate' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\DatabaseImportController::databaseMigrate'], [], [['text', '/installer/database-migrate']], [], [], []],
    'installer.finish' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\FinishController::finish'], [], [['text', '/installer/finish']], [], [], []],
    'installer.license' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\LicenseController::license'], [], [['text', '/installer/license']], [], [], []],
    'installer.requirements' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\RequirementsController::requirements'], [], [['text', '/installer/requirements']], [], [], []],
    'installer.language-selection' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\SelectLanguagesController::languageSelection'], [], [['text', '/installer']], [], [], []],
    'installer.configuration' => [[], ['_controller' => 'Shopware\\Core\\Installer\\Controller\\ShopConfigurationController::shopConfiguration'], [], [['text', '/installer/configuration']], [], [], []],
];
